# Note: This deployment shares the langflow-data PVC with langflow-openshift.yaml
# Both deployments must be applied, with langflow-openshift.yaml first to create the PVC
# Requires RWX storage class OR both pods scheduled on the same node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langflow-api
  labels:
    app: langflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langflow-api
  template:
    metadata:
      labels:
        app: langflow-api
    spec:
      # No securityContext with runAsUser - let OpenShift assign UID
      containers:
        - name: langflow
          image: langflowai/langflow:1.7.1
          ports:
            - containerPort: 7860
              name: http
          env:
            - name: LANGFLOW_HOST
              value: "0.0.0.0"
            - name: LANGFLOW_PORT
              value: "7860"
            - name: HOME
              value: "/app/data"
            - name: LANGFLOW_CONFIG_DIR
              value: "/app/data/.langflow"
            - name: LANGFLOW_DATABASE_URL
              value: "sqlite:////app/data/langflow.db"
            - name: LANGFLOW_ALEMBIC_LOG_FILE
              value: "/app/data/alembic.log"
            - name: LANGFLOW_AUTO_LOGIN
              value: "true"
            - name: LANGFLOW_SKIP_AUTH_AUTO_LOGIN
              value: "true"
            - name: LANGFLOW_BACKEND_ONLY
              value: "true"
          command:
            - langflow
            - run
            - --host
            - "0.0.0.0"
            - --port
            - "7860"
            - --backend-only
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /.cache
          startupProbe:
            httpGet:
              path: /health
              port: 7860
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /health
              port: 7860
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 7860
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: langflow-data
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: langflow-api
  labels:
    app: langflow-api
spec:
  type: ClusterIP
  ports:
    - port: 7860
      targetPort: 7860
      name: http
  selector:
    app: langflow-api
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: langflow-api
  labels:
    app: langflow-api
spec:
  to:
    kind: Service
    name: langflow-api
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
